cmake_minimum_required(VERSION 3.5)
project(Wego-Informatics)
set(CMAKE_CXX_STANDARD 17)

add_subdirectory(contests/contest_fall_2024)
add_subdirectory(contests/contest_spring_2025)
add_subdirectory(contests/contest_fall_2025)
add_subdirectory(contests/contest_spring_2026)

add_executable(unit01_test unit01/test.cpp)
add_executable(unit01_basic unit01/basic.cpp)
add_executable(unit02_cio unit02/cin_cout.cpp)
add_executable(unit02_var unit02/var_operators.cpp)
add_executable(unit03_string unit03/char_string.cpp)
add_executable(unit03_float unit03/float_double.cpp)
add_executable(unit04_if unit04/if_else.cpp)
add_executable(unit04_example unit04/shigure.cpp)
add_executable(unit05_while unit05/while.cpp)
add_executable(unit05_example unit05/miko.cpp)
add_executable(unit06_for unit06/for.cpp)
add_executable(unit07_array unit07/array.cpp)
add_executable(unit07_card unit07/card.cpp)
add_executable(unit07_sort_array unit07/sort_array.cpp)
add_executable(unit08_bad_nested_code unit08/reading_nested_code.cpp)
add_executable(unit08_example unit08/table.cpp)
add_executable(unit09_switch unit09/switch.cpp)
add_executable(unit09_example unit09/poker.cpp)
add_executable(unit10_review unit10/review.cpp)
add_executable(unit11_bitwise_operator unit11/bitwise_operator.cpp)
add_executable(unit12_2d_array unit12/2d_array.cpp)
add_executable(unit13_vector unit13/vector.cpp)
add_executable(unit14_lc26 unit14/leetcode26.cpp)
add_executable(unit14_lc27 unit14/leetcode27.cpp)
add_executable(unit14_lc58 unit14/leetcode58.cpp)
add_executable(unit15_set unit15/set.cpp)
add_executable(unit15_lc217_1 unit15/leetcode217_1.cpp)
add_executable(unit15_lc217_2 unit15/leetcode217_2.cpp)
add_executable(unit15_lc217_3 unit15/leetcode217_3.cpp)
add_executable(unit16_map unit16/map.cpp)
add_executable(unit17_sorting unit17/sorting.cpp)
add_executable(unit18_binary_search unit18/binary_search.cpp)
add_executable(unit18_lc35 unit18/leetcode35.cpp)
add_executable(unit18_lc35_2 unit18/leetcode35_2.cpp)
add_executable(unit18_lc1539 unit18/leetcode1539.cpp)
add_executable(unit18_lc2540 unit18/leetcode2540.cpp)
add_executable(unit19_lc1456 unit19/leetcode1456.cpp)
add_executable(unit19_lc187_1 unit19/leetcode187_1.cpp)
add_executable(unit19_lc187_2 unit19/leetcode187_2.cpp)
add_executable(unit19_lc3 unit19/leetcode3.cpp)
add_executable(unit20_lc509 unit20/leetcode509.cpp)
add_executable(unit20_gcd unit20/gcd.cpp)
add_executable(unit20_lc46 unit20/leetcode46.cpp)
add_executable(unit20_lc77 unit20/leetcode77.cpp)
add_executable(unit20_lc51 unit20/leetcode51.cpp)
add_executable(unit21_tree unit21/tree.cpp)
add_executable(unit21_order unit21/order.cpp)
add_executable(unit21_lc104 unit21/leetcode104.cpp)
add_executable(unit21_lc111 unit21/leetcode111.cpp)
add_executable(unit22_fibonacci unit22/fibonacci.cpp)
add_executable(unit22_lc70_1 unit22/leetcode70_1.cpp)
add_executable(unit22_lc70_2 unit22/leetcode70_2.cpp)
add_executable(unit22_lc70_3 unit22/leetcode70_3.cpp)
add_executable(unit22_lc746_2 unit22/leetcode746_2.cpp)
add_executable(unit22_lc746_1 unit22/leetcode746_1.cpp)
add_executable(unit22_hanoi unit22/hanoi.cpp)
add_executable(unit22_lc74_1 unit22/leetcode72_1.cpp)
add_executable(unit23_lc695_1 unit23/leetcode_695_1.cpp)
add_executable(unit23_lc695_2 unit23/leetcode_695_2.cpp)
add_executable(unit23_lc200_1 unit23/leetcode_200_1.cpp)
add_executable(unit23_lc200_2 unit23/leetcode_200_2.cpp)
add_executable(unit23_contest_2025f_lost unit23/contest_2025f_lost.cpp)
add_executable(unit23_lc_1971_1 unit23/leetcode_1971_1_tle.cpp)
add_executable(unit23_lc_1971_2 unit23/leetcode_1971_2_tle.cpp)
add_executable(unit23_lc_1971_3 unit23/leetcode_1971_3.cpp)
add_executable(unit23_lc_547_1 unit23/leetcode_547_1.cpp)
add_executable(unit23_lc_547_2 unit23/leetcode_547_2.cpp)
add_executable(unit24_coin unit24/coin.cpp)
add_executable(unit24_lc_948 unit24/leetcode_948.cpp)
add_executable(unit24_lc_743 unit24/leetcode_743.cpp)
