add_executable(c2025f_juice-validator validator/juice-validator.cpp)
add_executable(c2025f_juice-solution solution/juice-solution.cpp)
add_executable(c2025f_password-book-validator validator/password-book-validator.cpp)
add_executable(c2025f_password-book-solution solution/password-book-solution.cpp)
add_executable(c2025f_lost-validator validator/lost-validator.cpp)
add_executable(c2025f_lost-solution solution/lost-solution.cpp)
add_executable(c2025f_concert-validator validator/concert-validator.cpp)
add_executable(c2025f_concert-solution solution/concert-solution.cpp)
add_executable(c2025f_pie-validator validator/pie-validator.cpp)
add_executable(c2025f_pie-solution solution/pie-solution.cpp)
add_executable(c2025f_box-validator validator/box-validator.cpp)
add_executable(c2025f_box-solution solution/box-solution.cpp)